export const DISPLAY_ADDRESS_DETAILS = "DISPLAY_ADDRESS_DETAILS";
export const RETRIEVE_ADDRESS_DETAILS = "RETRIEVE_ADDRESS_DETAILS";
export const UPDATE_ADDRESS_DETAILS = "UPDATE_ADDRESS_DETAILS";
export const ADDRESS_INPUT = "ADDRESS_INPUT";
export const FORMAT_ADDRESS = "FORMAT_ADDRESS";
